live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0x662222"
duration = 40

# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'

[cursor]
style = "Block"
unfocused_hollow = true

[font.bold]
family = "Hack Nerd Font Mono"
style = "bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "bold italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "italic"

[font.normal]
family = "Hack Nerd Font Propo"
style = "regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "tmux"

[window.padding]
x = 4
y = 4
