format = """
$fill
$cmd_duration\
$git_commit\
$git_branch\
$git_metrics\
$git_status\
$git_state\
$character"""

continuation_prompt = "▶▶ "

[cmd_duration]
min_time = 0
show_milliseconds = true
show_notifications = true

[docker_context]
symbol = " "

[fill]
symbol = " "
style = "(fg:black bg:black)"

[git_branch]
symbol = " "

[git_metrics]
disabled = false

[git_commit]
only_detached = false
tag_disabled = false

[package]
format = "[$symbol $version]($style)"
symbol = "󰏗"
style = "fg:black bg:purple"
