set-window-option -g mode-keys vi # Set vim keys for copy mode navigation

# Set prefix Ctrl-A
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"

# Adapted settings from tmux-sensible
set -s escape-time 0
set -g history-limit 100000
set -g display-time 4000
set -g status-interval 1
set -g focus-events on
set -g mouse on

# Style status bar
set-option -g status-position top
set-option -g status-style fg=black,bg=yellow
set-option -g status-justify absolute-centre
set-option -g status-left "#[bg=black,fg=yellow]  #{=|-44|…;s|$HOME|~|:pane_current_path} "
set-option -g status-left-length 100
set-option -g status-right "#[bg=black,fg=yellow] 󰇅 #H   #S "
set-option -g status-right-length 50
set-option -g window-status-format "#[bg=yellow,fg=black] #I #W "
set-option -g window-status-current-format "#[bg=black,fg=yellow] #I #W "

# Switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Resize panes using vim direction keys
bind -r j resize-pane -D 10
bind -r k resize-pane -U 10
bind -r h resize-pane -L 10
bind -r l resize-pane -R 10

# use zshell
set -g default-command "/bin/zsh"

